### PR TITLE
fix!: Remove access to the svelte/internal API which is deprecated

### LINKED ISSUE #235: Svelte 5 support
When using the `Calendar` component in a Svelte 5 project it relies on `get_current_component()` from `svelte/internal` which has been removed.
https://github.com/vkurko/calendar/blob/d337436bfebf7ddac21b1d787d5300f44744ef4d/packages/core/src/Calendar.svelte#L4

A possible solution is presented [here](https://github.com/sveltejs/svelte/issues/3091) with an [example](https://github.com/sveltejs/svelte/issues/9189#issuecomment-1794764745).

Tested with Svelte `5.0.0-next.50`.

### PR DESCRIPTION
**Pull request by rgon**
FIXES #235 

Allows Svelte 5 compatibility.

BREAKING: removes support for the destroy() method on <Calendar />. Alternative: wrap the calendar in an {#if notDestroyed}<Calendar />{/if} block.

### CODE REVIEW

File: packages/core/src/lib/utils.js [hunk 1]
```diff
@@ -29,3 +29,46 @@ export function symbol() {
...
+ * @param {(event?: Event) => void} handler
+ * @param {any} call_handler_immediately
+ */
+export function listen(target, events, handler, call_handler_immediately = true) {
+	if (call_handler_immediately) {
+		handler();
+	}
+
+	for (var name of events) {
+		target.addEventListener(name, handler);
```
Comment (dummdidumm) [inline packages/core/src/lib/utils.js:65]: I recommend using Svelte's `on` method from `svelte/events` for this instead. Handles a few edge cases around event delegation which may or may not be relevant in this repo (I haven't checked)

**Comment by JonasFocke01** [comment]
@vkurko It would be realy helpfull if you could publish this to the npm registry

**Comment by vkurko** [comment]
> @vkurko It would be realy helpfull if you could publish this to the npm registry

Sorry, I wanted to fix some things before publishing the code, but I haven't had enough free time to do it yet. I think I'll definitely finish it this week.
